version: "3.7"
services:
  app-backend:
    restart: always
    image: t-learn:1.0.0-SNAPSHOT
    container_name: t-learn-backend
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      QUARKUS_DATASOURCE_USERNAME: "t-learn"
      QUARKUS_DATASOURCE_PASSWORD: "t-learn"
      QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://postgres:5432/t_learn_db"

  postgres:
    restart: always
    image: postgres:13
    container_name: t-learn-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "t-learn"
      POSTGRES_PASSWORD: "t-learn"
      POSTGRES_DB: "t_learn_db"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
