version: "3.7"
services:
  app-backend:
    image: t-learn:1.0.0-SNAPSHOT
    expose:
      - 8080
    depends_on:
      - postgres
    environment:
      QUARKUS_DATASOURCE_USERNAME: "t-learn"
      QUARKUS_DATASOURCE_PASSWORD: "t-learn"
      QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://postgres:5432/t_learn_db"

  postgres:
    image: postgres:13
    expose:
      - 5432
    environment:
      POSTGRES_USER: "t-learn"
      POSTGRES_PASSWORD: "t-learn"
      POSTGRES_DB: "t_learn_db"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
