create sequence category_sequence start 1 increment 1;
insert into Category(id, name) values(nextval('category_sequence'), 'agile methoden');
insert into Category(id, name) values(nextval('category_sequence'), 'Agiles Arbeiten');
insert into Category(id, name) values(nextval('category_sequence'), 'Agilität');
insert into Category(id, name) values(nextval('category_sequence'), 'AR/VR');
insert into Category(id, name) values(nextval('category_sequence'), 'backend');
insert into Category(id, name) values(nextval('category_sequence'), 'Beratung');
insert into Category(id, name) values(nextval('category_sequence'), 'Business-Skills');
insert into Category(id, name) values(nextval('category_sequence'), 'Cloud');
insert into Category(id, name) values(nextval('category_sequence'), 'Coaching');
insert into Category(id, name) values(nextval('category_sequence'), 'Content-Management-Systeme');
insert into Category(id, name) values(nextval('category_sequence'), 'Controlling');
insert into Category(id, name) values(nextval('category_sequence'), 'Data Science');
insert into Category(id, name) values(nextval('category_sequence'), 'Datenbanken');
insert into Category(id, name) values(nextval('category_sequence'), 'Design');
insert into Category(id, name) values(nextval('category_sequence'), 'Design Thinking');
insert into Category(id, name) values(nextval('category_sequence'), 'E-Commerce-Systeme');
insert into Category(id, name) values(nextval('category_sequence'), 'Edge-Device-Architekturen');
insert into Category(id, name) values(nextval('category_sequence'), 'employer branding');
insert into Category(id, name) values(nextval('category_sequence'), 'Enterprise-Architekturen');
insert into Category(id, name) values(nextval('category_sequence'), 'Feedback');
insert into Category(id, name) values(nextval('category_sequence'), 'Framework');
insert into Category(id, name) values(nextval('category_sequence'), 'Frontend');
insert into Category(id, name) values(nextval('category_sequence'), 'Führungsmodelle');
insert into Category(id, name) values(nextval('category_sequence'), 'Gehaltsverandlung');
insert into Category(id, name) values(nextval('category_sequence'), 'Geoinformationssysteme');
insert into Category(id, name) values(nextval('category_sequence'), 'Go');
insert into Category(id, name) values(nextval('category_sequence'), 'Green IT');
insert into Category(id, name) values(nextval('category_sequence'), 'Hard Skills');
insert into Category(id, name) values(nextval('category_sequence'), 'HTML;XML;CSS;');
insert into Category(id, name) values(nextval('category_sequence'), 'Infrastruktur');
insert into Category(id, name) values(nextval('category_sequence'), 'interkulturelle Kompetenzen');
insert into Category(id, name) values(nextval('category_sequence'), 'IoT');
insert into Category(id, name) values(nextval('category_sequence'), 'KI');
insert into Category(id, name) values(nextval('category_sequence'), 'Kommunikation');
insert into Category(id, name) values(nextval('category_sequence'), 'Konfliktmanagement');
insert into Category(id, name) values(nextval('category_sequence'), 'Körpersprache');
insert into Category(id, name) values(nextval('category_sequence'), 'Map Applications');
insert into Category(id, name) values(nextval('category_sequence'), 'Marketing');
insert into Category(id, name) values(nextval('category_sequence'), 'Marketingkommunikation');
insert into Category(id, name) values(nextval('category_sequence'), 'marketingstrategien');
insert into Category(id, name) values(nextval('category_sequence'), 'Messaging');
insert into Category(id, name) values(nextval('category_sequence'), 'Methodik');
insert into Category(id, name) values(nextval('category_sequence'), 'Microservices');
insert into Category(id, name) values(nextval('category_sequence'), 'Mobile');
insert into Category(id, name) values(nextval('category_sequence'), 'OKR');
insert into Category(id, name) values(nextval('category_sequence'), 'Online Marketing');
insert into Category(id, name) values(nextval('category_sequence'), 'Oracle');
insert into Category(id, name) values(nextval('category_sequence'), 'persönliche Kompetenzen');
insert into Category(id, name) values(nextval('category_sequence'), 'PHP');
insert into Category(id, name) values(nextval('category_sequence'), 'Präsentation');
insert into Category(id, name) values(nextval('category_sequence'), 'Produktdesign');
insert into Category(id, name) values(nextval('category_sequence'), 'Produktmanagement');
insert into Category(id, name) values(nextval('category_sequence'), 'QA');
insert into Category(id, name) values(nextval('category_sequence'), 'React;Angular');
insert into Category(id, name) values(nextval('category_sequence'), 'Rhetorik');
insert into Category(id, name) values(nextval('category_sequence'), 'Scrum');
insert into Category(id, name) values(nextval('category_sequence'), 'Security');
insert into Category(id, name) values(nextval('category_sequence'), 'Selbstorganisation');
insert into Category(id, name) values(nextval('category_sequence'), 'Selbstwahrnehmung');
insert into Category(id, name) values(nextval('category_sequence'), 'Social Media');
insert into Category(id, name) values(nextval('category_sequence'), 'Soft Skills');
insert into Category(id, name) values(nextval('category_sequence'), 'Software-Architektur');
insert into Category(id, name) values(nextval('category_sequence'), 'Storytelling');
insert into Category(id, name) values(nextval('category_sequence'), 'System-Architektur');
insert into Category(id, name) values(nextval('category_sequence'), 'Technologien');
insert into Category(id, name) values(nextval('category_sequence'), 'Testing/ QA');
insert into Category(id, name) values(nextval('category_sequence'), 'UI & Web Design');
insert into Category(id, name) values(nextval('category_sequence'), 'User Experience (UX)');
insert into Category(id, name) values(nextval('category_sequence'), 'User Interface (UI)');
insert into Category(id, name) values(nextval('category_sequence'), 'UX');
insert into Category(id, name) values(nextval('category_sequence'), 'UX/UI Design');
insert into Category(id, name) values(nextval('category_sequence'), 'Vertriebsgespräche');
insert into Category(id, name) values(nextval('category_sequence'), 'Web');
insert into Category(id, name) values(nextval('category_sequence'), 'Zeit-und Selbstmanagement');
